#Default configuration for cskyv1eb-softmmu

CONFIG_SEMIHOSTING=y
# Boards:
#
CONFIG_SMARTL=y
CONFIG_CSKY_VIRT=y
CONFIG_YUNVOICE_V2=y
CONFIG_TRILOBITE=y
CONFIG_TRILOBITE_V2=y
CONFIG_SMART_CARD=y
CONFIG_HOBBIT1_V2=y
CONFIG_DEIMOS=y
CONFIG_SMARTH=y
CONFIG_DUMMYH=y
